version: "3"
services:
  discord-chat-bot:
    build:
      context: docker-compose
      dockerfile: Dockerfile
    container_name: discord-chat-bot-azure
    restart: unless-stopped
    environment:
      - CHAT_SERVICE=azure
      - DISCORD_BOT_TOKEN=
      - DISCORD_CLIENT_ID=
      - ALLOWED_SERVER_IDS=